const countryActionsTypes = {
  SET_COUNTRIES: "SET_COUNTRIES",
  SET_CURRENT_COUNTRIES: "SET_CURRENT_COUNTRIES",
  SET_CURRENT_REGION: "SET_CURRENT_REGION",
  TOGGLE_SHOW_DROP_DOWN: "TOGGLE_SHOW_DROP_DOWN",
  RESET_REGION_COUNTRIES: "RESET_REGION_COUNTRIES",
};

export default countryActionsTypes;
