const todoActionsTypes = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  TOGGLE_COMPLETE_TODO: "TOGGLE_COMPLETE_TODO",
  CHANGE_FILTER: "CHANGE_FILTER",
  CLEAR_COMPLETED: "CLEAR_COMPLETED",
  SET_CURRENT_TODOS_IDS: "SET_CURRENT_TODOS_IDS",
  SET_TODOS_IDS: "SET_TODOS_IDS",
};

export default todoActionsTypes;
